name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Установка Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24

      - name: Установка зависимостей
        run: go mod tidy

      - name: Запуск тестов
        run: go test ./...

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Сборка и Пуш Docker-образа
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "${{ secrets.DOCKER_NAME }}/todo-app:latest"
